### ISSUE TITLE
Add projects in C++/Python/Flutter

### ISSUE THREAD

**Issue by sohilkhanduja** [sohilkhanduja/HacktoberFest_DSA#10]

**Comment by sohilkhanduja** [comment]
@Srivastava57Harsh You have to add your minor/major project that you have done in any of the following programming languages/frameworks. For example, you can add any app that you might have made using Flutter.

**Comment by sohilkhanduja** [comment]
Yes sure @Yash-RajSingh. Go ahead.

**Comment by Yash-RajSingh** [comment]
> Yes sure @Yash-RajSingh. Go ahead.

Hey I've added a graphical periodic table in C++ in the PR #11 . Kindly review it and merge @sohilkhanduja

**Comment by sohilkhanduja** [comment]
Yes merged it. It was a great project for contributing in Open Source. @Yash-RajSingh

**Comment by Srivastava57Harsh** [comment]
@sohilkhanduja I have added a simple (1 v 1) Tic Tac Toe program build in python using pygame and numpy module, kindly check
